---
title: "Data Analysis Project"
author: "Marcel Vaz"
date: "November 23, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R2jags)
library(lattice)
library(ggplot2)
load("AddBurnin.RData")
```

```{r}
# Creating logit function:
logit <- function(x) {
  log(x/(1-x))
      }

logit(0.975)
logit(0.025)
logit(0.950)


# Model:
sink("model.txt")
cat("
  model{
        for(i in 1:N){
          for(j in 1:2){
            y[i,j] ~ dbin(pie[i,j],n[i,j])
            logit(pie[i,j]) <- mu[i] + (2*j - 3) * delta[i]/2
          }
          mu[i] ~ dnorm(mu0, tau.mu)
          delta[i] ~ dnorm(delta0, tau.delta)
        }
    mu0 ~ dnorm(0, 1/3.36)
    tau.mu ~ dunif(0, 1/3.36)
    delta0 ~ dnorm(0, 1/2.17)
    tau.delta ~ dunif(0, 1/2.17)
    }    
  ", fill = TRUE)
sink()

nn <- matrix(c(71,174,52,53,107,142,49,238,86,103,49,241,357,348,516,512,186,218,36,41,70,80), ncol= 2, byrow=TRUE)
yy <- matrix(c(4,1,3,2,12,3,15,19,18,5,11,10,4,9,25,11,20,15,17,25,4,5), ncol=2, byrow=TRUE)

yy/nn

lmod = lm(as.numeric(yy/nn) ~ as.factor(rep(0:1,11)))
summary(lmod)


data <- list(n=nn, y=yy, N=11)
pies = matrix(rep(0.5,22), ncol= 2, byrow=TRUE)
inits <- rep(
list(list(
    pie = pies,
    mu = rep(0,11), delta = rep(0,11),
    mu0 = 0, tau.mu = 0, delta0 = 0, tau.delta = 0))
   ,3)
params <- c("pie[1:11,1:2]","mu[1:11]","delta[1:11]","mu0","delta0","tau.mu","tau.delta")

model.out = jags(data=data, inits= NULL, parameter=params, "model.txt", 
               n.chains=3, n.iter=101000, n.burnin=0, n.thin=20, DIC=F)

#Treat the first 1000 iterations as a burn in	
Output = AddBurnin(model.out$BUGSoutput$sims.array, burnin=1000,n.thin=1)

# Table:
summary <- Output$Burnin.Summary[25:46, -5]

rownames(summary) <- c("Stunt-St 1", "Stunt-St 2","Stunt-St 3", "Stunt-St 4","Stunt-St 5","Stunt-St 6", "Stunt-St 7", "Stunt-St 8", "Stunt-St 9", "Stunt-St 10", "Stunt-St 11", "CABG- St 1", "CABG- St 2", "CABG- St 3", "CABG- St 4", "CABG- St 5", "CABG- St 6", "CABG- St 7", "CABG- St 8", "CABG- St 9", "CABG- St 10", "CABG- St 11")
colnames(summary) <- c("Mean", "SD", "2.5%", "97.5%")
knitr::kable(summary, digits=4, caption ="JAGS output for treatment and study probabilities of death")

# Autocorrelations
# ACF plots for deltas:
par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 1], lag.max= 160, main="delta0")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 2], lag.max= 160, main="delta1")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 3], lag.max= 160, main="delta2")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 4], lag.max= 160, main="delta3")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 5], lag.max= 160, main="delta4")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 6], lag.max= 160, main="delta5")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 7], lag.max= 160, main="delta6")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 8], lag.max= 160, main="delta7")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 9], lag.max= 160, main="delta8")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 10], lag.max= 160, main="delta9")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 11], lag.max= 160, main="delta10")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 12], lag.max= 160, main="delta11")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 13], lag.max= 160, main="mu0")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 14], lag.max= 160, main="mu1")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 15], lag.max= 160, main="mu2")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 16], lag.max= 160, main="mu3")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 17], lag.max= 160, main="mu4")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 18], lag.max= 160, main="mu5")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 19], lag.max= 160, main="mu6")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 20], lag.max= 160, main="mu7")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 21], lag.max= 160, main="mu8")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 22], lag.max= 160, main="mu9")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 23], lag.max= 160, main="mu10")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 24], lag.max= 160, main="mu11")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 25], lag.max= 160, main="pie[1,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 26], lag.max= 160, main="pie[2,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 27], lag.max= 160, main="pie[3,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 28], lag.max= 160, main="pie[4,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 29], lag.max= 160, main="pie[5,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 30], lag.max= 160, main="pie[6,1]")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 31], lag.max= 160, main="pie[7,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 32], lag.max= 160, main="pie[8,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 33], lag.max= 160, main="pie[9,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 34], lag.max= 160, main="pie[10,1]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 35], lag.max= 160, main="pie[11,1]")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 36], lag.max= 160, main="pie[1,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 37], lag.max= 160, main="pie[2,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 38], lag.max= 160, main="pie[3,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 39], lag.max= 160, main="pie[4,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 40], lag.max= 160, main="pie[5,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 41], lag.max= 160, main="pie[6,2]")

par(mfrow=c(2,3))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 42], lag.max= 160, main="pie[7,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 43], lag.max= 160, main="pie[8,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 44], lag.max= 160, main="pie[9,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 45], lag.max= 160, main="pie[10,2]")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 46], lag.max= 160, main="pie[11,2]")

par(mfrow=c(1,2))
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 47], lag.max= 160, main="tau.delta")
acf(model.out$BUGSoutput$sims.array[1:5000, 1, 48], lag.max= 160, main="tau.mu")

#Time series plots
par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 1], type="l", ylab="delta0")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 1], type="l", col="blue", ylab="delta0")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 1], type="l", col="red", ylab="delta0")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 2], type="l", ylab="delta1")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 2], type="l", col="blue", ylab="delta1")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 2], type="l", col="red", ylab="delta1")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 3], type="l", ylab="delta2")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 3], type="l", col="blue", ylab="delta2")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 3], type="l", col="red", ylab="delta2")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 4], type="l", ylab="delta3")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 4], type="l", col="blue", ylab="delta3")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 4], type="l", col="red", ylab="delta3")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 5], type="l", ylab="delta4")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 5], type="l", col="blue", ylab="delta4")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 5], type="l", col="red", ylab="delta4")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 6], type="l", ylab="delta5")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 6], type="l", col="blue", ylab="delta5")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 6], type="l", col="red", ylab="delta5")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 7], type="l", ylab="delta6")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 7], type="l", col="blue", ylab="delta6")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 7], type="l", col="red", ylab="delta6")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 8], type="l", ylab="delta7")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 8], type="l", col="blue", ylab="delta7")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 8], type="l", col="red", ylab="delta7")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 9], type="l", ylab="delta8")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 9], type="l", col="blue", ylab="delta8")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 9], type="l", col="red", ylab="delta8")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 10], type="l", ylab="delta9")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 10], type="l", col="blue", ylab="delta9")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 10], type="l", col="red", ylab="delta9")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 11], type="l", ylab="delta10")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 11], type="l", col="blue", ylab="delta10")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 11], type="l", col="red", ylab="delta10")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 12], type="l", ylab="delta11")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 12], type="l", col="blue", ylab="delta11")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 12], type="l", col="red", ylab="delta11")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 13], type="l", ylab="mu0")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 13], type="l", col="blue", ylab="mu0")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 13], type="l", col="red", ylab="mu0")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 14], type="l", ylab="mu1")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 14], type="l", col="blue", ylab="mu1")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 14], type="l", col="red", ylab="mu1")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 15], type="l", ylab="mu2")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 15], type="l", col="blue", ylab="mu2")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 15], type="l", col="red", ylab="mu2")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 16], type="l", ylab="mu3")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 16], type="l", col="blue", ylab="mu3")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 16], type="l", col="red", ylab="mu3")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 17], type="l", ylab="mu4")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 17], type="l", col="blue", ylab="mu4")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 17], type="l", col="red", ylab="mu4")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 18], type="l", ylab="mu5")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 18], type="l", col="blue", ylab="mu5")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 18], type="l", col="red", ylab="mu5")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 19], type="l", ylab="mu6")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 19], type="l", col="blue", ylab="mu6")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 19], type="l", col="red", ylab="mu6")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 20], type="l", ylab="mu7")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 20], type="l", col="blue", ylab="mu7")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 20], type="l", col="red", ylab="mu7")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 21], type="l", ylab="mu8")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 21], type="l", col="blue", ylab="mu8")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 21], type="l", col="red", ylab="mu8")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 22], type="l", ylab="mu9")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 22], type="l", col="blue", ylab="mu9")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 22], type="l", col="red", ylab="mu9")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 23], type="l", ylab="mu10")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 23], type="l", col="blue", ylab="mu10")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 23], type="l", col="red", ylab="mu10")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 24], type="l", ylab="mu11")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 24], type="l", col="blue", ylab="mu11")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 24], type="l", col="red", ylab="mu11")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 25], type="l", ylab="pi[1,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 25], type="l", col="blue", ylab="pi[1,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 25], type="l", col="red", ylab="pi[1,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 26], type="l", ylab="pi[2,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 26], type="l", col="blue", ylab="pi[2,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 26], type="l", col="red", ylab="pi[2,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 27], type="l", ylab="pi[3,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 27], type="l", col="blue", ylab="pi[3,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 27], type="l", col="red", ylab="pi[3,1]")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 28], type="l", ylab="pi[4,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 28], type="l", col="blue", ylab="pi[4,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 28], type="l", col="red", ylab="pi[4,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 29], type="l", ylab="pi[5,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 29], type="l", col="blue", ylab="pi[5,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 29], type="l", col="red", ylab="pi[5,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 30], type="l", ylab="pi[6,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 30], type="l", col="blue", ylab="pi[6,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 30], type="l", col="red", ylab="pi[6,1]")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 30], type="l", ylab="pi[7,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 30], type="l", col="blue", ylab="pi[7,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 30], type="l", col="red", ylab="pi[7,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 31], type="l", ylab="pi[8,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 31], type="l", col="blue", ylab="pi[8,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 31], type="l", col="red", ylab="pi[8,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 32], type="l", ylab="pi[9,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 32], type="l", col="blue", ylab="pi[9,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 32], type="l", col="red", ylab="pi[9,1]")

par(mfrow=c(2,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 32], type="l", ylab="pi[10,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 32], type="l", col="blue", ylab="pi[10,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 32], type="l", col="red", ylab="pi[10,1]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 33], type="l", ylab="pi[11,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 33], type="l", col="blue", ylab="pi[11,1]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 33], type="l", col="red", ylab="pi[11,1]")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 34], type="l", ylab="pi[1,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 34], type="l", col="blue", ylab="pi[1,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 34], type="l", col="red", ylab="pi[1,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 35], type="l", ylab="pi[2,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 35], type="l", col="blue", ylab="pi[2,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 35], type="l", col="red", ylab="pi[2,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 36], type="l", ylab="pi[3,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 36], type="l", col="blue", ylab="pi[3,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 36], type="l", col="red", ylab="pi[3,2]")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 37], type="l", ylab="pi[4,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 37], type="l", col="blue", ylab="pi[4,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 37], type="l", col="red", ylab="pi[4,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 38], type="l", ylab="pi[5,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 38], type="l", col="blue", ylab="pi[5,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 38], type="l", col="red", ylab="pi[5,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 39], type="l", ylab="pi[6,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 39], type="l", col="blue", ylab="pi[6,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 39], type="l", col="red", ylab="pi[6,2]")

par(mfrow=c(3,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 40], type="l", ylab="pi[7,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 40], type="l", col="blue", ylab="pi[7,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 40], type="l", col="red", ylab="pi[7,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 41], type="l", ylab="pi[8,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 41], type="l", col="blue", ylab="pi[8,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 41], type="l", col="red", ylab="pi[8,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 42], type="l", ylab="pi[9,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 42], type="l", col="blue", ylab="pi[9,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 42], type="l", col="red", ylab="pi[9,2]")

par(mfrow=c(2,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 43], type="l", ylab="pi[10,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 43], type="l", col="blue", ylab="pi[10,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 43], type="l", col="red", ylab="pi[10,2]")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 44], type="l", ylab="pi[11,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 44], type="l", col="blue", ylab="pi[11,2]")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 44], type="l", col="red", ylab="pi[11,2]")

par(mfrow=c(2,1))
plot(model.out$BUGSoutput$sims.array[1:1000, 1, 45], type="l", ylab="tau.delta")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 45], type="l", col="blue", ylab="tau.delta")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 45], type="l", col="red", ylab="tau.delta")

plot(model.out$BUGSoutput$sims.array[1:1000, 1, 46], type="l", ylab="tau.mu")
lines(model.out$BUGSoutput$sims.array[1:1000, 2, 46], type="l", col="blue", ylab="tau.mu")
lines(model.out$BUGSoutput$sims.array[1:1000, 3, 46], type="l", col="red", ylab="tau.mu")

dev.off()

# Stent vs CABG together:
temp2 <- Output$Burnin.sims.matrix
library(faraway)

j0 <- ilogit(temp2[,13] - temp2[,1]/2)
j1 <- ilogit(temp2[,13] + temp2[,1]/2)
plot(density(j0), ylim= c(0,15), main= "", xlab="Probability")
lines(density(j1), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")
title("Density of death probability", outer=T, line=-3)

# Density plots:
plot(density(temp2[,25]), ylim= c(0,85), main= "Stent vs CABG- Study 1", xlab="Probability")
lines(density(temp2[,36]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,26]), ylim= c(0,25), main= "Stent vs CABG- Study 2", xlab="Probability")
lines(density(temp2[,37]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,27]), ylim= c(0,40), main= "Stent vs CABG- Study 3", xlab="Probability")
lines(density(temp2[,38]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,28]), xlim= c(0, 0.5), ylim= c(0,25), main= "Stent vs CABG- Study 4", xlab="Probability")
lines(density(temp2[,39]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,29]), xlim= c(0, 0.4), ylim= c(0,21), main= "Stent vs CABG- Study 5", xlab="Probability")
lines(density(temp2[,40]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,30]), xlim= c(0, 0.4), ylim= c(0,35), main= "Stent vs CABG- Study 6", xlab="Probability")
lines(density(temp2[,41]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,31]), xlim= c(0, 0.4), ylim= c(0,70), main= "Stent vs CABG- Study 7", xlab="Probability")
lines(density(temp2[,42]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,32]), xlim= c(0, 0.4), ylim= c(0,63), main= "Stent vs CABG- Study 8", xlab="Probability")
lines(density(temp2[,43]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,33]), xlim= c(0, 0.4), ylim= c(0,25), main= "Stent vs CABG- Study 9", xlab="Probability")
lines(density(temp2[,44]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,34]), ylim= c(0,10), main= "Stent vs CABG- Study 10", xlab="Probability")
lines(density(temp2[,45]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

plot(density(temp2[,35]), xlim= c(0, 0.4), ylim= c(0,20), main= "Stent vs CABG- Study 11", xlab="Probability")
lines(density(temp2[,46]), col= 2)
legend("topright", legend = c("Stent", "CABG"), lty= 1, col= 1:2, bty="n")

# Sensitivity analysis:

```

